spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mybatis_plus?characterEncoding=utf8&useSSL=false&nullCatalogMeansCurrent=true&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource  #当前数据源操作类型
#spring:
## 配置数据源信息
#  datasource:
#    dynamic:
## 设置默认的数据源或者数据源组,默认值即为master
#    primary: master
## 严格匹配数据源,默认false.true未匹配到指定数据源时抛异常,false使用默认数据源
#    strict: false
#    datasource:
#      master:
#        url: jdbc:mysql://localhost:3306/mybatis_plus?characterEncoding=utf-
#          8&useSSL=false
#        driver-class-name: com.mysql.cj.jdbc.Driver
#        username: root
#        password: 123456
#      slave_1:
#        url: jdbc:mysql://localhost:3306/mybatis_plus_1?characterEncoding=utf-
#          8&useSSL=false
#        driver-class-name: com.mysql.cj.jdbc.Driver
#        username: root
#        password: 123456
#端口号修改为8888 默认为8080
server:
  port: 8888


mybatis-plus:
  configuration:
    # 驼峰 默认开启
#    map-underscore-to-camel-case: false
    # 配置MyBatis日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 全局配置相关
  global-config:
    db-config:
      # 配置MyBatis-Plus的主键策略
      id-type: auto
    # 配置MyBatis-Plus操作表的默认前缀
    #        table-prefix: t_

    # 配置类型别名所对应的包
  type-aliases-package: com.example.uml_work.bean
  # 扫描通用枚举的包
  type-enums-package: com.example.uml_work.enums


